# Generated by Django 4.2.2 on 2023-10-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_resume_project_description_resume_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='achivements',
            field=models.TextField(default='YourDefaultHere', max_length=500),
        ),
    ]
