# Generated by Django 4.2.2 on 2023-10-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_resume_achivements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stuprnlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_fname', models.CharField(max_length=100)),
                ('stu_lname', models.CharField(max_length=100)),
                ('prnno', models.CharField(max_length=100)),
            ],
        ),
    ]
