# Generated by Django 4.2.2 on 2023-10-27 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_stuprnlog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stuprnlog',
            new_name='Stuprnno',
        ),
    ]
