# Generated by Django 4.2.2 on 2023-11-13 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0008_stuprnno_stu_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='address',
            new_name='dob',
        ),
    ]
