# Generated by Django 4.2.2 on 2023-11-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0009_rename_address_resume_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='degins',
            field=models.TextField(default='YourDefaultHere', max_length=500),
        ),
        migrations.AddField(
            model_name='resume',
            name='degper',
            field=models.TextField(default='YourDefaultHere', max_length=500),
        ),
        migrations.AddField(
            model_name='resume',
            name='degyear',
            field=models.TextField(default='YourDefaultHere', max_length=500),
        ),
        migrations.AddField(
            model_name='resume',
            name='hscdeg',
            field=models.TextField(default='YourDefaultHere', max_length=500),
        ),
        migrations.AddField(
            model_name='resume',
            name='hscins',
            field=models.TextField(default='YourDefaultHere', max_length=500),
        ),
        migrations.AddField(
            model_name='resume',
            name='hscper',
            field=models.TextField(default='YourDefaultHere', max_length=500),
        ),
        migrations.AddField(
            model_name='resume',
            name='hscyear',
            field=models.TextField(default='YourDefaultHere', max_length=500),
        ),
        migrations.AddField(
            model_name='resume',
            name='sscper',
            field=models.TextField(default='YourDefaultHere', max_length=500),
        ),
        migrations.AddField(
            model_name='resume',
            name='sscyear',
            field=models.TextField(default='YourDefaultHere', max_length=500),
        ),
    ]
