# Generated by Django 4.2.2 on 2023-11-14 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0010_resume_degins_resume_degper_resume_degyear_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='skills',
            new_name='proskills',
        ),
    ]
