# Generated by Django 4.2.2 on 2023-11-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0011_rename_skills_resume_proskills'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='famskills',
            field=models.TextField(default='YourDefaultHere', max_length=1000),
        ),
        migrations.AddField(
            model_name='resume',
            name='famtech',
            field=models.TextField(default='YourDefaultHere', max_length=1000),
        ),
        migrations.AddField(
            model_name='resume',
            name='protech',
            field=models.TextField(default='YourDefaultHere', max_length=1000),
        ),
        migrations.AlterField(
            model_name='resume',
            name='proskills',
            field=models.TextField(default='YourDefaultHere', max_length=1000),
        ),
    ]
